name: Python (build pull request)

on: [pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main

    - name: Install Python 3.13
      uses: actions/setup-python@main
      with:
        python-version: '3.13'

    - name: Build sdist and wheel.
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build wheel
        python -m build
      shell: pwsh

    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: dist-${{ runner.os }}
        path: dist/*
