name: Python (build pull request)

on: [pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      # Only build on CPython 3.13
      CIBW_BUILD: cp313-*
    steps:
    - uses: actions/checkout@main

    - name: Install Python 3.13
      uses: actions/setup-python@main
      with:
        python-version: '3.13'

    - name: Build sdist and wheels.
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build wheel cibuildwheel
        python -m cibuildwheel --archs all --output-dir dist
        python -m build --sdist
      shell: pwsh

    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: dist-${{ runner.os }}
        path: dist/*
